on:
  push:
    branches:
      - main

workspace:
  id: 52
  project: server-1-project

services:
  - name: server
    type: container
    build:
      repo: https://github.com/mohammada-huma/test-fastapi
      branch: main
      dockerfile: Dockerfile
      context: .
    ingress:
      host: mo-test-1789.sbx.huma.com
      paths: ["/"]
      port: 8000
